name: 'Setup-Boost'
description: 'Clone and bootstrap Boost super-project'
runs:
  using: composite
  steps:
    - name: Bootstrap Boost
      shell: bash
      run: |
        REF=${GITHUB_BASE_REF:-$GITHUB_REF}
        BOOST_BRANCH=develop && [ "$REF" == "master" ] && BOOST_BRANCH=master || true
        cd ..
        git clone -b $BOOST_BRANCH --depth 1 https://github.com/boostorg/boost.git boost-root
        cd boost-root
        #cp -r $GITHUB_WORKSPACE/* libs/gil
        git submodule update --init tools/boostdep
        python tools/boostdep/depinst/depinst.py --git_args "--jobs 3" gil
        ./bootstrap.sh
        ./b2 -d0 headers
    - name: Create user-config.jam
      shell: bash
      run: |
        echo "using ${{matrix.toolset}} : : ${{matrix.compiler}} ;" > ~/user-config.jam
        cat ~/user-config.jam
