name: CI

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

env:
  NET_RETRY_COUNT: 5

jobs:
  posix-cxxstd-14:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          # C++14 is default in GCC 6.1 through 10
          - { compiler: g++-6,        cxxstd: '14', toolset: gcc-6,  install: g++-6,      os: ubuntu-18.04 }
          - { compiler: g++-7,        cxxstd: '14', toolset: gcc-7,  install: g++-7,      os: ubuntu-18.04 }
          - { compiler: g++-8,        cxxstd: '14', toolset: gcc-8,  install: g++-8,      os: ubuntu-18.04 }
          - { compiler: g++-9,        cxxstd: '14', toolset: gcc-9,  install: g++-9,      os: ubuntu-18.04 }
          - { compiler: g++-10,       cxxstd: '14', toolset: gcc-10, install: g++-10,     os: ubuntu-20.04 }
          - { compiler: clang++-3.9,  cxxstd: '14', toolset: clang,  install: clang-3.9,  os: ubuntu-18.04 }
          - { compiler: clang++-4.0,  cxxstd: '14', toolset: clang,  install: clang-4.0,  os: ubuntu-18.04 }
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: sudo apt-get -o Acquire::Retries=$NET_RETRY_COUNT install -y ${{matrix.install}}
      - name: Compiler version
        run: ${{matrix.compiler}} --version || ${{matrix.toolset}} --version

  posix-cxxstd-17:
    needs: posix-cxxstd-14
    strategy:
      fail-fast: false
      matrix:
        include:
          # C++17 is default in GCC 11 through 12
          - { compiler: g++-11,       cxxstd: '17', toolset: gcc-11, install: g++-11,     os: ubuntu-20.04 }
          - { compiler: g++-12,       cxxstd: '17', toolset: gcc-12, install: g++-12,     os: ubuntu-22.04 }
          - { compiler: clang++-5.0,  cxxstd: '17', toolset: clang,  install: clang-5.0,  os: ubuntu-18.04 }
          - { compiler: clang++-6.0,  cxxstd: '17', toolset: clang,  install: clang-6.0,  os: ubuntu-18.04 }
          - { compiler: clang++-7,    cxxstd: '17', toolset: clang,  install: clang-7,    os: ubuntu-18.04 }
          - { compiler: clang++-8,    cxxstd: '17', toolset: clang,  install: clang-8,    os: ubuntu-20.04 }
          - { compiler: clang++-9,    cxxstd: '17', toolset: clang,  install: clang-9,    os: ubuntu-20.04 }
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        if: matrix.install
        run: sudo apt-get -o Acquire::Retries=$NET_RETRY_COUNT install -y ${{matrix.install}}
      - name: Compiler Version
        run: |
          gcc --version
          g++ --version
          clang++ --version
          ${{matrix.compiler}} --version

  posix-cxxstd-20:
    needs: posix-cxxstd-17
    strategy:
      fail-fast: false
      matrix:
        include:
          # C++20 is available in GCC 10 through 12
          - { compiler: g++-10,       cxxstd: '20', toolset: gcc-10, install: g++-10,     os: ubuntu-20.04 }
          - { compiler: g++-11,       cxxstd: '20', toolset: gcc-11, install: g++-11,     os: ubuntu-20.04 }
          - { compiler: g++-12,       cxxstd: '20', toolset: gcc-12, install: g++-12,     os: ubuntu-22.04 }
          - { compiler: clang++-10,   cxxstd: '20', toolset: clang,  install: clang-10,   os: ubuntu-20.04 }
          - { compiler: clang++-11,   cxxstd: '20', toolset: clang,  install: clang-11,   os: ubuntu-20.04 }
          - { compiler: clang++-12,   cxxstd: '20', toolset: clang,  install: clang-12,   os: ubuntu-20.04 }
          - { compiler: clang++-13,   cxxstd: '20', toolset: clang,  install: clang-13,   os: ubuntu-22.04 }
          - { compiler: clang++-14,   cxxstd: '20', toolset: clang,  install: clang-14,   os: ubuntu-22.04 }
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        if: matrix.install
        run: sudo apt-get -o Acquire::Retries=$NET_RETRY_COUNT install -y ${{matrix.install}}
      - name: Compiler Version
        run: |
          gcc --version
          g++ --version
          clang++ --version
          ${{matrix.compiler}} --version

  windows-cxxstd-14:
    needs: posix-cxxstd-14
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        include:
          - { toolset: msvc-14.0, cxxstd: '14', os: windows-2019 }
          - { toolset: msvc-14.2, cxxstd: '14', os: windows-2019 }
          - { toolset: msvc-14.3, cxxstd: '14', os: windows-2022 }
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2

  windows-cxxstd-17:
    needs: windows-cxxstd-14
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        include:
          - { toolset: msvc-14.2, cxxstd: '17', os: windows-2019 }
          - { toolset: msvc-14.3, cxxstd: '17', os: windows-2022 }
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2

  windows-cxxstd-20:
    needs: windows-cxxstd-17
    defaults:
      run:
        shell: cmd
    strategy:
      fail-fast: false
      matrix:
        include:
          - { toolset: msvc-14.2, cxxstd: '20', os: windows-2019 }
          - { toolset: msvc-14.3, cxxstd: '20,latest', os: windows-2022 }
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
