name: CI

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:

env:
  NET_RETRY_COUNT: 5

jobs:
  posix-cxxstd-14:
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          # C++14 is default in GCC 6.1 through 10
          - { compiler: g++-6,        cxxstd: '14', toolset: gcc-6,  install: g++-6,      os: ubuntu-18.04 }
          - { compiler: g++-7,        cxxstd: '14', toolset: gcc-7,  install: g++-7,      os: ubuntu-18.04 }
          - { compiler: g++-8,        cxxstd: '14', toolset: gcc-8,  install: g++-8,      os: ubuntu-18.04 }
          - { compiler: g++-9,        cxxstd: '14', toolset: gcc-9,  install: g++-9,      os: ubuntu-18.04 }
          - { compiler: g++-10,       cxxstd: '14', toolset: gcc-10, install: g++-10,     os: ubuntu-20.04 }
          - { compiler: clang++-3.6,  cxxstd: '14', toolset: clang,  install: clang-3.6,  os: ubuntu-20.04, container: 'ubuntu:16.04' }
          - { compiler: clang++-3.7,  cxxstd: '14', toolset: clang,  install: clang-3.7,  os: ubuntu-20.04, container: 'ubuntu:16.04' }
          - { compiler: clang++-3.8,  cxxstd: '14', toolset: clang,  install: clang-3.8,  os: ubuntu-20.04, container: 'ubuntu:16.04' }
          - { compiler: clang++-3.9,  cxxstd: '14', toolset: clang,  install: clang-3.9,  os: ubuntu-18.04 }
          - { compiler: clang++-4.0,  cxxstd: '14', toolset: clang,  install: clang-4.0,  os: ubuntu-18.04 }
    runs-on: ${{matrix.os}}
    steps:
      - name: Setup environment
        run: |
            if [ -f "/etc/debian_version" ]; then
                echo "DEBIAN_FRONTEND=noninteractive" >> $GITHUB_ENV
                export DEBIAN_FRONTEND=noninteractive
            fi
            if [ -n "${{matrix.container}}" ] && [ -f "/etc/debian_version" ]; then
                apt-get -o Acquire::Retries=$NET_RETRY_COUNT update
                apt-get -o Acquire::Retries=$NET_RETRY_COUNT install -y sudo software-properties-common
                # Need (newer) git, and the older Ubuntu container may require requesting the key manually using port 80
                apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys E1DD270288B4E6030699E45FA1715D88E1DF1F24
                for i in {1..${NET_RETRY_COUNT:-3}}; do sudo -E add-apt-repository -y ppa:git-core/ppa && break || sleep 10; done
                apt-get -o Acquire::Retries=$NET_RETRY_COUNT update
                apt-get -o Acquire::Retries=$NET_RETRY_COUNT install -y g++ python libpython-dev git
            fi
      - uses: actions/checkout@v2
      - name: Install packages
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test || sleep 10
          sudo apt-get -o Acquire::Retries=$NET_RETRY_COUNT update
          sudo apt-get -o Acquire::Retries=$NET_RETRY_COUNT install -y ${{matrix.install}}
      - name: Compiler version
        run: ${{matrix.compiler}} --version || ${{matrix.toolset}} --version

  posix-cxxstd-17:
    needs: posix-cxxstd-14
    strategy:
      fail-fast: false
      matrix:
        include:
          # C++17 is default in GCC 11 through 12
          - { compiler: g++-11,       cxxstd: '17', toolset: gcc-11, install: g++-11,     os: ubuntu-20.04 }
          - { compiler: g++-12,       cxxstd: '17', toolset: gcc-12, install: g++-12,     os: ubuntu-20.04 }
          - { compiler: clang++-5.0,  cxxstd: '17', toolset: clang,  install: clang-5.0,  os: ubuntu-18.04 }
          - { compiler: clang++-6.0,  cxxstd: '17', toolset: clang,  install: clang-6.0,  os: ubuntu-18.04 }
          - { compiler: clang++-7,    cxxstd: '17', toolset: clang,  install: clang-7,    os: ubuntu-18.04 }
          - { compiler: clang++-8,    cxxstd: '17', toolset: clang,  install: clang-8,    os: ubuntu-20.04 }
          - { compiler: clang++-9,    cxxstd: '17', toolset: clang,  install: clang-9,    os: ubuntu-20.04 }
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        if: matrix.install
        run: sudo apt install ${{matrix.install}}
      - name: Compiler Version
        run: ${{matrix.compiler}} --version

  posix-cxxstd-20:
    needs: posix-cxxstd-17
    strategy:
      fail-fast: false
      matrix:
        include:
          # C++20 is available in GCC 10 through 12
          - { compiler: g++-10,       cxxstd: '20', toolset: gcc-10, install: g++-10,     os: ubuntu-20.04 }
          - { compiler: g++-11,       cxxstd: '20', toolset: gcc-11, install: g++-11,     os: ubuntu-20.04 }
          - { compiler: g++-12,       cxxstd: '20', toolset: gcc-12, install: g++-12,     os: ubuntu-22.04 }
          - { compiler: clang++-10,   cxxstd: '20', toolset: clang,  install: clang-10,   os: ubuntu-20.04 }
          - { compiler: clang++-11,   cxxstd: '20', toolset: clang,  install: clang-11,   os: ubuntu-20.04 }
          - { compiler: clang++-12,   cxxstd: '20', toolset: clang,  install: clang-12,   os: ubuntu-20.04 }
          - { compiler: clang++-13,   cxxstd: '20', toolset: clang,  install: clang-13,   os: ubuntu-22.04 }
          - { compiler: clang++-14,   cxxstd: '20', toolset: clang,  install: clang-14,   os: ubuntu-22.04 }
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        if: matrix.install
        run: sudo apt install ${{matrix.install}}
      - name: Compiler Version
        run: ${{matrix.compiler}} --version
